### ISSUE TITLE
Should probably be jasmine-wrap.

### ISSUE THREAD

**Issue by gdborton** [ljharb/jest-wrap#2]
Seeing this issue - https://github.com/facebook/jest/issues/3155 made me remember that the internal test runner is actually Jasmine.  Looks like jest will be test runner agnostic in the future, and people will need different `-wrap` libs depending on which they use.

**Comment by ljharb** [comment]
I think until just his test run or agnostic, jest–wrap will still be needed.  It's beneficial to have the appropriate peer dependency requirements and test coverage in the meantime.

Certainly creating jasmine-wrap is a good idea also.

**Comment by gdborton** [comment]
Closing this out as Jest has cut out jasmine completely as of version 20.
