### ISSUE TITLE
Jest 20 incompatability

### ISSUE THREAD

**Issue by gdborton** [ljharb/jest-wrap#6]
Jest 20 was released a few days ago, and it has corrected the issue around afterEach/afterAll so that they run in the correct order by default (we're currently reversing for correctness in 18/19).

We can unreverse, which will un-break jest 20, but will break 18/19 OR we can drop support for 18/19 and cut a new major release.... do you have a preference?

**Comment by gdborton** [comment]
Alternatively we could use a package to dive into jest and find out what version it is, but I think that's icky.

**Comment by ljharb** [comment]
Hmm, tests seem to pass with d847c0be695d71262e39451ed0294fe5bab39146.

**Comment by ljharb** [comment]
whoops, i missed something. i'll keep working on it.

**Comment by ljharb** [comment]
Is there any chance there's something reflectable about jest where we can differentiate this ordering? Can you link to the PR/commit that fixed this issue in jest?

**Comment by gdborton** [comment]
Sure - https://github.com/facebook/jest/pull/3275
Also, it's in the change log for 20 - https://github.com/facebook/jest/blob/master/CHANGELOG.md
> Fixed lifecycle hooks to make afterAll hooks operate the same as afterEach. (#3275)
